spring:
  application:
    name: heyue-admin
  profiles:
    active: dev #默认开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml