spring:
  datasource:
    url: jdbc:mysql://101.33.232.150:3306/heyue?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: heyue
    password: heyue8888
    druid:
      initial-size: 5 #连接池大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet:
        login-username: druid
        login-password: druid